Install Git from homebrew/core instead of caskroom/cask
Fixes:
> Error: Cask 'git' is unavailable: No Cask with this name exists. Did you mean one of these?